# -*- coding: utf-8 -*-
"""Bab 13 - Pebryan.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BlTR80FwwvlOrDgNa82SZyC5H_en4I6j

BellmanFord
"""

# Membuat class Graph
class Graph:

    # Constructor
    def __init__(self, vertices):

        # Jumlah vertex
        self.V = vertices

        # Menyimpan seluruh edge
        self.graph = []

        # Menyimpan daftar node
        self.nodes = []


    # Menambahkan edge beserta bobotnya
    def add_edge(self, s, d, w):

        # s = source
        # d = destination
        # w = weight
        self.graph.append([s, d, w])


    # Menambahkan node
    def addNode(self, value):

        self.nodes.append(value)


    # Menampilkan hasil jarak terpendek
    def print_solution(self, dist):

        print("Vertex Distance from Source")

        for key, value in dist.items():
            print(" ", key, " : ", value)


    # Algoritma Bellman-Ford
    def bellmanFord(self, src):

        # Inisialisasi semua jarak = tak hingga
        dist = {
            i: float("Inf")
            for i in self.nodes
        }

        # Jarak node awal = 0
        dist[src] = 0

        # Relaksasi seluruh edge sebanyak V-1 kali
        for _ in range(self.V - 1):

            for s, d, w in self.graph:

                if (dist[s] != float("Inf") and
                        dist[s] + w < dist[d]):

                    dist[d] = dist[s] + w

        # Mengecek adanya negative cycle
        for s, d, w in self.graph:

            if (dist[s] != float("Inf") and
                    dist[s] + w < dist[d]):

                print("Graph contains negative cycle")
                return

        # Menampilkan hasil
        self.print_solution(dist)


# PROGRAM UTAMA
# Membuat graph dengan 5 vertex
g = Graph(5)

# Menambahkan node
g.addNode("A")
g.addNode("B")
g.addNode("C")
g.addNode("D")
g.addNode("E")

# Menambahkan edge berbobot
g.add_edge("A", "C", 6)
g.add_edge("A", "D", 6)
g.add_edge("B", "A", 3)
g.add_edge("C", "D", 1)
g.add_edge("D", "C", 2)
g.add_edge("D", "B", 1)
g.add_edge("E", "B", 4)
g.add_edge("E", "D", 2)

# Menjalankan Bellman-Ford
g.bellmanFord("E")

"""BinarySearch"""

# Searching Algorithm - Binary Search

# Mengimpor modul math
import math


# Fungsi Binary Search
def binarySearch(array, value):

    # Index awal
    start = 0

    # Index akhir
    end = len(array) - 1

    # Menentukan posisi tengah
    middle = math.floor((start + end) / 2)

    # Melakukan pencarian selama data belum ditemukan
    # dan ruang pencarian masih tersedia
    while not (array[middle] == value) and start <= end:

        # Jika nilai yang dicari lebih kecil
        if value < array[middle]:

            # Geser batas kanan
            end = middle - 1

        else:
            # Geser batas kiri
            start = middle + 1

        # Menghitung kembali posisi tengah
        middle = math.floor((start + end) / 2)

        # Untuk melihat proses pencarian
        # print(start, middle, end)

    # Jika data ditemukan
    if array[middle] == value:
        return middle

    # Jika data tidak ditemukan
    else:
        return -1

# PROGRAM UTAMA
# Array harus sudah terurut (ascending)
custArray = [8, 9, 12, 15, 17, 19, 20, 21, 28]

# Mencari angka 15
print(binarySearch(custArray, 15))

"""Dijkstra"""

# Dijkstra Algorithm

# Mengimpor modul heapq (Priority Queue)
import heapq


# ==========================
# CLASS EDGE
# ==========================

class Edge:
    def __init__(self, weight, start_vertex, target_vertex):

        # Bobot edge
        self.weight = weight

        # Node asal
        self.start_vertex = start_vertex

        # Node tujuan
        self.target_vertex = target_vertex


# ==========================
# CLASS NODE
# ==========================

class Node:
    def __init__(self, name):

        # Nama node
        self.name = name

        # Status apakah sudah dikunjungi
        self.visited = False

        # Menyimpan node sebelumnya
        self.predecessor = None

        # Daftar edge yang terhubung
        self.neighbors = []

        # Jarak minimum dari source
        self.min_distance = float("inf")


    # Agar heapq dapat membandingkan node
    def __lt__(self, other_node):
        return self.min_distance < other_node.min_distance


    # Menambahkan edge
    def add_edge(self, weight, destination_vertex):

        edge = Edge(weight, self, destination_vertex)
        self.neighbors.append(edge)


# ==========================
# CLASS DIJKSTRA
# ==========================

class Dijkstra:

    def __init__(self):

        # Priority Queue
        self.heap = []


    # Menghitung shortest path
    def calculate(self, start_vertex):

        # Jarak node awal = 0
        start_vertex.min_distance = 0

        # Masukkan ke priority queue
        heapq.heappush(self.heap, start_vertex)

        while self.heap:

            # Mengambil node dengan jarak terkecil
            actual_vertex = heapq.heappop(self.heap)

            if actual_vertex.visited:
                continue

            # Memeriksa seluruh tetangga
            for edge in actual_vertex.neighbors:

                start = edge.start_vertex
                target = edge.target_vertex

                # Menghitung jarak baru
                new_distance = start.min_distance + edge.weight

                # Jika lebih kecil, update jarak
                if new_distance < target.min_distance:

                    target.min_distance = new_distance
                    target.predecessor = start

                    # Masukkan kembali ke priority queue
                    heapq.heappush(self.heap, target)

            actual_vertex.visited = True


    # Menampilkan hasil shortest path
    def get_shortest_path(self, vertex):

        print("The shortest path distance :", vertex.min_distance)

        actual_vertex = vertex

        while actual_vertex is not None:
            print(actual_vertex.name, end=" ")
            actual_vertex = actual_vertex.predecessor


# ==========================
# MEMBUAT NODE
# ==========================

nodeA = Node("A")
nodeB = Node("B")
nodeC = Node("C")
nodeD = Node("D")
nodeE = Node("E")
nodeF = Node("F")
nodeG = Node("G")
nodeH = Node("H")


# ==========================
# MEMBUAT EDGE
# ==========================

nodeA.add_edge(6, nodeB)
nodeA.add_edge(10, nodeC)
nodeA.add_edge(9, nodeD)

nodeB.add_edge(5, nodeD)
nodeB.add_edge(16, nodeE)
nodeB.add_edge(13, nodeF)

nodeC.add_edge(6, nodeD)
nodeC.add_edge(5, nodeH)
nodeC.add_edge(21, nodeG)

nodeD.add_edge(8, nodeF)
nodeD.add_edge(7, nodeH)

nodeE.add_edge(10, nodeG)

nodeF.add_edge(4, nodeE)
nodeF.add_edge(12, nodeG)

nodeH.add_edge(2, nodeF)
nodeH.add_edge(14, nodeG)


# ==========================
# MENJALANKAN ALGORITMA
# ==========================

algorithm = Dijkstra()

# Source = A
algorithm.calculate(nodeA)

# Menampilkan shortest path menuju G
algorithm.get_shortest_path(nodeG)

"""DijkstraSSSP"""

# Dijkstra Algorithm (Dictionary Version)

from collections import defaultdict


# ==========================
# CLASS GRAPH
# ==========================

class Graph:

    def __init__(self):

        # Menyimpan seluruh node
        self.nodes = set()

        # Adjacency List
        self.edges = defaultdict(list)

        # Menyimpan bobot setiap edge
        self.distances = {}


    # Menambahkan node
    def addNode(self, value):

        self.nodes.add(value)


    # Menambahkan edge beserta bobot
    def addEdge(self, fromNode, toNode, distance):

        self.edges[fromNode].append(toNode)
        self.distances[(fromNode, toNode)] = distance


# ==========================
# DIJKSTRA ALGORITHM
# ==========================

def dijkstra(graph, initial):

    # Menyimpan jarak terpendek
    visited = {initial: 0}

    # Menyimpan predecessor (jalur)
    path = defaultdict(list)

    # Salinan seluruh node
    nodes = set(graph.nodes)

    while nodes:

        # Mencari node dengan jarak terkecil
        minNode = None

        for node in nodes:

            if node in visited:

                if minNode is None:
                    minNode = node

                elif visited[node] < visited[minNode]:
                    minNode = node

        if minNode is None:
            break

        nodes.remove(minNode)

        currentWeight = visited[minNode]

        # Relaksasi seluruh tetangga
        for edge in graph.edges[minNode]:

            weight = currentWeight + graph.distances[(minNode, edge)]

            if edge not in visited or weight < visited[edge]:

                visited[edge] = weight

                # Menyimpan predecessor
                path[edge] = [minNode]

    return visited, path


# ==========================
# PROGRAM UTAMA
# ==========================

customGraph = Graph()

customGraph.addNode("A")
customGraph.addNode("B")
customGraph.addNode("C")
customGraph.addNode("D")
customGraph.addNode("E")
customGraph.addNode("F")
customGraph.addNode("G")

customGraph.addEdge("A", "B", 2)
customGraph.addEdge("A", "C", 5)
customGraph.addEdge("B", "C", 6)
customGraph.addEdge("B", "D", 1)
customGraph.addEdge("B", "E", 3)
customGraph.addEdge("C", "F", 8)
customGraph.addEdge("D", "E", 4)
customGraph.addEdge("E", "G", 9)
customGraph.addEdge("F", "G", 7)

print(dijkstra(customGraph, "A"))

"""DisjointSet"""

# Disjoint Set (Union-Find)

class DisjointSet:

    # Constructor
    def __init__(self, vertices):

        # Menyimpan daftar vertex
        self.vertices = vertices

        # Menyimpan parent setiap vertex
        self.parent = {}

        # Awalnya setiap vertex adalah parent dirinya sendiri
        for v in vertices:
            self.parent[v] = v

        # Menyimpan rank (tinggi pohon)
        self.rank = dict.fromkeys(vertices, 0)


    # Mencari root (representative) suatu himpunan
    def find(self, item):

        if self.parent[item] == item:
            return item
        else:
            return self.find(self.parent[item])


    # Menggabungkan dua himpunan
    def union(self, x, y):

        # Mencari root masing-masing
        xroot = self.find(x)
        yroot = self.find(y)

        # Union by Rank
        if self.rank[xroot] < self.rank[yroot]:

            self.parent[xroot] = yroot

        elif self.rank[xroot] > self.rank[yroot]:

            self.parent[yroot] = xroot

        else:

            self.parent[yroot] = xroot
            self.rank[xroot] += 1


# ==========================
# PROGRAM UTAMA
# ==========================

vertices = ["A", "B", "C", "D", "E"]

ds = DisjointSet(vertices)

# Menggabungkan A dan B
ds.union("A", "B")

# Menggabungkan A dan C
ds.union("A", "C")

# Mencari root dari A
print(ds.find("A"))

"""FloydWarshall"""

# Floyd-Warshall Algorithm

# Nilai tak hingga (Infinity)
INF = 9999


# ==========================
# MENAMPILKAN HASIL
# ==========================

def printSolution(nV, distance):

    for i in range(nV):

        for j in range(nV):

            if distance[i][j] == INF:
                print("INF", end=" ")

            else:
                print(distance[i][j], end="  ")

        print()


# ==========================
# FLOYD-WARSHALL
# ==========================

def floydWarshall(nV, G):

    # Matriks jarak awal
    distance = G

    # Memilih setiap vertex sebagai perantara
    for k in range(nV):

        # Vertex asal
        for i in range(nV):

            # Vertex tujuan
            for j in range(nV):

                # Memilih jarak yang lebih pendek
                distance[i][j] = min(
                    distance[i][j],
                    distance[i][k] + distance[k][j]
                )

    # Menampilkan hasil
    printSolution(nV, distance)


# ==========================
# PROGRAM UTAMA
# ==========================

G = [
    [0,   8, INF, 1],
    [INF, 0,   1, INF],
    [4, INF,   0, INF],
    [INF, 2,   9, 1]
]

floydWarshall(4, G)

"""Kruskal"""

# Kruskal Algorithm

# Mengimpor Disjoint Set (Union-Find)


# ==========================
# CLASS GRAPH
# ==========================

class Graph:

    # Constructor
    def __init__(self, vertices):

        # Jumlah vertex
        self.V = vertices

        # Menyimpan seluruh edge
        self.graph = []

        # Menyimpan daftar node
        self.nodes = []

        # Menyimpan hasil Minimum Spanning Tree
        self.MST = []


    # Menambahkan edge
    def addEdge(self, s, d, w):

        # s = source
        # d = destination
        # w = weight
        self.graph.append([s, d, w])


    # Menambahkan node
    def addNode(self, value):

        self.nodes.append(value)


    # Menampilkan hasil MST
    def printSolution(self, s, d, w):

        print("Minimum Spanning Tree :")

        for s, d, w in self.MST:
            print("%s - %s : %s" % (s, d, w))


    # Algoritma Kruskal
    def kruskalAlgo(self):

        # i = index edge
        # e = jumlah edge yang dipilih
        i, e = 0, 0

        # Membuat Disjoint Set
        ds = DisjointSet(self.nodes)

        # Mengurutkan edge berdasarkan bobot
        self.graph = sorted(
            self.graph,
            key=lambda item: item[2]
        )

        # Memilih edge hingga MST berisi V-1 edge
        while e < self.V - 1:

            s, d, w = self.graph[i]
            i += 1

            x = ds.find(s)
            y = ds.find(d)

            # Jika tidak membentuk siklus
            if x != y:

                e += 1

                self.MST.append([s, d, w])

                ds.union(x, y)

        self.printSolution(s, d, w)


# ==========================
# PROGRAM UTAMA
# ==========================

g = Graph(5)

g.addNode("A")
g.addNode("B")
g.addNode("C")
g.addNode("D")
g.addNode("E")

g.addEdge("A", "B", 5)
g.addEdge("A", "C", 13)
g.addEdge("A", "E", 15)

g.addEdge("B", "A", 5)
g.addEdge("B", "C", 10)
g.addEdge("B", "D", 8)

g.addEdge("C", "A", 13)
g.addEdge("C", "B", 10)
g.addEdge("C", "E", 20)
g.addEdge("C", "D", 6)

g.addEdge("D", "B", 8)
g.addEdge("D", "C", 6)

g.addEdge("E", "A", 15)
g.addEdge("E", "C", 20)

g.kruskalAlgo()

"""LinearSearch"""

# Searching Algorithms - Linear Search
# Linear Search mencari data dengan memeriksa setiap elemen
# secara berurutan dari awal hingga akhir list.

def linearSearch(array, value):
    # Melakukan perulangan pada seluruh elemen array
    for i in range(len(array)):
        # Jika elemen yang dicari ditemukan
        if array[i] == value:
            # Mengembalikan indeks elemen tersebut
            return i
    # Jika data tidak ditemukan, mengembalikan -1
    return -1


# Contoh penggunaan
print(linearSearch([20, 40, 30, 50, 90], 90))

"""Prims"""

# Prim's Algorithm in Python
# Algoritma Prim digunakan untuk mencari Minimum Spanning Tree (MST),
# yaitu kumpulan sisi dengan total bobot minimum yang menghubungkan
# seluruh simpul pada graph tanpa membentuk siklus.

import sys

class Graph:
    def __init__(self, vertexNum, edges, nodes):
        # Matriks bobot antar simpul
        self.edges = edges

        # Daftar nama simpul
        self.nodes = nodes

        # Jumlah simpul
        self.vertexNum = vertexNum

        # Menyimpan hasil Minimum Spanning Tree (MST)
        self.MST = []

    def printSolution(self):
        # Menampilkan hasil MST
        print("Edge : Weight")
        for s, d, w in self.MST:
            print("%s -> %s: %s" % (s, d, w))

    def primsAlgo(self):
        # Menandai simpul yang sudah dikunjungi
        visited = [0] * self.vertexNum

        # Menghitung jumlah edge yang sudah masuk ke MST
        edgeNum = 0

        # Memulai dari simpul pertama
        visited[0] = True

        # Ulangi sampai semua simpul terhubung
        while edgeNum < self.vertexNum - 1:
            min = sys.maxsize

            # Mencari edge dengan bobot terkecil
            # yang menghubungkan simpul yang sudah dikunjungi
            # ke simpul yang belum dikunjungi
            for i in range(self.vertexNum):
                if visited[i]:
                    for j in range(self.vertexNum):
                        if (not visited[j]) and self.edges[i][j]:
                            if min > self.edges[i][j]:
                                min = self.edges[i][j]
                                s = i
                                d = j

            # Menambahkan edge ke MST
            self.MST.append([self.nodes[s], self.nodes[d], self.edges[s][d]])

            # Tandai simpul tujuan sebagai sudah dikunjungi
            visited[d] = True

            # Tambah jumlah edge yang sudah dipilih
            edgeNum += 1

        # Menampilkan hasil MST
        self.printSolution()


# Matriks bobot graph
edges = [
    [0, 10, 20, 0, 0],
    [10, 0, 30, 5, 0],
    [20, 30, 0, 15, 6],
    [0, 5, 15, 0, 8],
    [0, 0, 6, 8, 0]
]

# Nama simpul
nodes = ["A", "B", "C", "D", "E"]

# Membuat objek Graph
g = Graph(5, edges, nodes)

# Menjalankan Algoritma Prim
g.primsAlgo()

"""SSSP"""

# Breadth First Search (BFS) untuk mencari jalur (path)
# BFS menelusuri graph secara melebar (level per level)
# hingga menemukan simpul tujuan.

class Graph:
    def __init__(self, gdict=None):
        # Menyimpan graph dalam bentuk adjacency list
        if gdict is None:
            gdict = {}
        self.gdict = gdict

    def bfs(self, start, end):
        # Queue menyimpan jalur (path), bukan hanya simpul
        queue = []

        # Memulai pencarian dari node awal
        queue.append([start])

        # Selama queue masih berisi jalur
        while queue:
            # Mengambil jalur pertama (FIFO)
            path = queue.pop(0)

            # Mengambil node terakhir pada jalur
            node = path[-1]

            # Jika node tujuan ditemukan, kembalikan jalurnya
            if node == end:
                return path

            # Menambahkan seluruh tetangga ke queue
            for adjacent in self.gdict.get(node, []):
                new_path = list(path)      # Menyalin jalur sebelumnya
                new_path.append(adjacent)  # Menambahkan node tetangga
                queue.append(new_path)

        # Jika tujuan tidak ditemukan
        return None


# Graph dalam bentuk adjacency list
customDict = {
    "a": ["b", "c"],
    "b": ["d", "g"],
    "c": ["d", "e"],
    "d": ["f"],
    "e": ["f"],
    "g": ["f"]
}

# Membuat objek Graph
g = Graph(customDict)

# Mencari jalur dari a ke z
print(g.bfs("a", "z"))